# Generated by Django 5.1 on 2024-09-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Country',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
